---
layout: 2018/spring
---

= Speller

> For this assignment you will need to use a tool called valgrind. *Sad to say, `valgrind` does not work consistently on Macs*. So in case you are using a Mac, we recommend you to sign up for a GitHub account over at: https://github.com/signup. Then use that GitHub account to login over at https://code.cs50.io/. This will give you an online editor (Visual Studio Code) and a Linux terminal. From there, whenever you want to run valgrind upload your code to https://code.cs50.io/ and run`valgrind` there instead. Alternatively, for this one assignment, you can choose to work in https://code.cs50.io/ altogether. 

== tl;dr

Implement a program that spell-checks a file, per the below.

[source,subs=quotes]
----
$ [underline]#./speller texts/lalaland.txt#
MISSPELLED WORDS

[...]
AHHHHHHHHHHHHHHHHHHHHHHHHHHHT
[...]
Shangri
[...]
fianc
[...]
Sebastian's
[...]

WORDS MISSPELLED:
WORDS IN DICTIONARY:
WORDS IN TEXT:
TIME IN load:
TIME IN check:
TIME IN size:
TIME IN unload:
TIME IN TOTAL:
----

== Distribution

=== Downloading

[source,subs="macros"]
----
$ curl -LO https://github.com/minprog/programmeren-1/raw/2022/problems/speller/speller.zip
$ unzip speller.zip
$ rm speller.zip
$ cd speller
$ ls
dictionaries/  dictionary.c  dictionary.h  keys/  Makefile  README.md  speller.c  texts/
----

=== Understanding

Theoretically, on input of size _n_, an algorithm with a running time of _n_ is asymptotically equivalent, in terms of _O_, to an algorithm with a running time of pass:[2]_n_. In the real world, though, the fact of the matter is that the latter feels twice as slow as the former.

The challenge ahead of you is to implement the fastest spell checker you can! By "fastest," though, we're talking actual, real-world, noticeable time—none of that asymptotic stuff this time.

In `speller.c`, we've put together a program that's designed to spell-check a file after loading a dictionary of words from disk into memory. Unfortunately, we didn't quite get around to implementing the loading part. Or the checking part. Both (and a bit more) we leave to you! But first, a tour.

==== `dictionary.{c,h}`

Open up `dictionary.h`. Declared in that file are four functions; take note of what each should do. Now open up `dictionary.c`. Notice that we've implemented those four functions, but only barely, just enough for this code to compile. Your job, ultimately, is to re-implement those functions as cleverly as possible so that this spell checker works as advertised. And fast!

==== `Makefile`

Recall that make automates compilation of your code so that you don't have to execute clang manually along with a whole bunch of switches. However, as your programs grow in size, make won't be able to infer from context anymore how to compile your code; you'll need to start telling make how to compile your program, particularly when they involve multiple source (i.e., .c) files, as in the case of this problem. And so we'll utilize a Makefile, a configuration file that tells make exactly what to do. Open up Makefile, and you should see four lines:

1. The first line tells make to execute the subsequent lines whenever you yourself execute make speller (or just make).
2. The second line tells make how to compile speller.c into machine code (i.e., speller.o).
3. The third line tells make how to compile dictionary.c into machine code (i.e., dictionary.o).
4. The fourth line tells make to link speller.o and dictionary.o in a file called speller.

> Be sure to compile speller by executing make speller (or just make). Executing make dictionary won't work!

==== `speller.c`

Okay, next open up `speller.c` and spend some time looking over the code and comments therein. You won't need to change anything in this file, but you should understand it nonetheless. Notice how, by way of `getrusage`, we'll be "benchmarking" (i.e., timing the execution of) your implementations of `check`, `load`, `size`, and `unload`. Also notice how we go about passing `check`, word by word, the contents of some file to be spell-checked. Ultimately, we report each misspelling in that file along with a bunch of statistics.

Notice, incidentally, that we have defined the usage of `speller` to be

[source]
----
Usage: speller [dictionary] text
----

where `dictionary` is assumed to be a file containing a list of lowercase words, one per line, and `text` is a file to be spell-checked. As the brackets suggest, provision of `dictionary` is optional; if this argument is omitted, `speller` will use `dictionaries/large` by default. In other words, running

[source]
----
./speller text
----

will be equivalent to running

[source]
----
./speller dictionaries/large text
----

where `text` is the file you wish to spell-check. Suffice it to say, the former is easier to type! (Of course, `speller` will not be able to load any dictionaries until you implement `load` in `dictionary.c`! Until then, you'll see *Could not load*.)

Within the default dictionary, mind you, are 143,091 words, all of which must be loaded into memory! In fact, take a peek at that file to get a sense of its structure and size. Notice that every word in that file appears in lowercase (even, for simplicity, proper nouns and acronyms). From top to bottom, the file is sorted lexicographically, with only one word per line (each of which ends with `\n`). No word is longer than 45 characters, and no word appears more than once. During development, you may find it helpful to provide `speller` with a `dictionary` of your own that contains far fewer words, lest you struggle to debug an otherwise enormous structure in memory. In `dictionaries/small` is one such dictionary. To use it, execute

[source]
----
./speller dictionaries/small text
----

where `text` is the file you wish to spell-check. Don't move on until you're sure you understand how `speller` itself works!

Odds are, you didn't spend enough time looking over `speller.c`. Go back one square and walk yourself through it again!

==== `texts/`

So that you can test your implementation of `speller`, we've also provided you with a whole bunch of texts, among them the script from _La La Land_, the text of the Affordable Care Act, three million bytes from Tolstoy, some excerpts from _The Federalist Papers_ and Shakespeare, the entirety of the King James V Bible and the Koran, and more. So that you know what to expect, open and skim each of those files, all of which are in a directory called `texts` within your `module5` directory.

Now, as you should know from having read over `speller.c` carefully, the output of `speller`, if executed with, say,

[source]
----
./speller texts/lalaland.txt
----

will eventually resemble the below. For information's sake, we've excerpted some examples of "misspellings." And lest we spoil the fun, we've omitted our own statistics for now.

[source]
----
MISSPELLED WORDS

[...]
AHHHHHHHHHHHHHHHHHHHHHHHHHHHT
[...]
Shangri
[...]
fianc
[...]
Sebastian's
[...]

WORDS MISSPELLED:
WORDS IN DICTIONARY:
WORDS IN TEXT:
TIME IN load:
TIME IN check:
TIME IN size:
TIME IN unload:
TIME IN TOTAL:
----

`TIME IN load` represents the number of seconds that `speller` spends executing your implementation of `load`. `TIME IN check` represents the number of seconds that `speller` spends, in total, executing your implementation of `check`. `TIME IN size` represents the number of seconds that `speller` spends executing your implementation of `size`. `TIME IN unload` represents the number of seconds that `speller` spends executing your implementation of `unload`. `TIME IN TOTAL` is the sum of those four measurements.

*Note that these times may vary somewhat across executions of `speller`, depending on what else your computer is doing, even if you don't change your code.*

Incidentally, to be clear, by "misspelled" we simply mean that some word is not in the `dictionary` provided.

== Questions

Open up `README.md` and answer each of the questions therein.

== Specification

Alright, the challenge now before you is to implement `load`, `check`, `size`, and `unload` as efficiently as possible, in such a way that `TIME IN load`, `TIME IN check`, `TIME IN size`, and `TIME IN unload` are all minimized. To be sure, it's not obvious what it even means to be minimized, inasmuch as these benchmarks will certainly vary as you feed `speller` different values for `dictionary` and for `text`. But therein lies the challenge, if not the fun, of this problem. This problem is your chance to design. Although we invite you to minimize space, your ultimate enemy is time. But before you dive in, some specifications from us.

* You may not alter `speller.c`.
* You may alter `dictionary.c` (and, in fact, must in order to complete the implementations of `load`, `check`, `size`, and `unload`), but you may not alter the declarations of `load`, `check`, `size`, or `unload`.
* You may alter `dictionary.h`, but you may not alter the declarations of `load`, `check`, `size`, or `unload`.
* You may alter `Makefile`.
* You may add functions to `dictionary.c` or to files of your own creation so long as all of your code compiles via `make`.
* Your implementation of `check` must be case-insensitive. In other words, if `foo` is in dictionary, then `check` should return true given any capitalization thereof; none of `foo`, `foO`, `fOo`, `fOO`, `fOO`, `Foo`, `FoO`, `FOo`, and `FOO` should be considered misspelled.
* Capitalization aside, your implementation of `check` should only return `true` for words actually in `dictionary`. Beware hard-coding common words (e.g., `the`), lest we pass your implementation a `dictionary` without those same words. Moreover, the only possessives allowed are those actually in `dictionary`. In other words, even if `foo` is in `dictionary`, `check` should return `false` given `foo's` if `foo's` is not also in `dictionary`.
* You may assume that `check` will only be passed strings with alphabetical characters and/or apostrophes.
* You may assume that any `dictionary` passed to your program will be structured exactly like ours, lexicographically sorted from top to bottom with one word per line, each of which ends with `\n`. You may also assume that `dictionary` will contain at least one word, that no word will be longer than `LENGTH` (a constant defined in `dictionary.h`) characters, that no word will appear more than once, and that each word will contain only lowercase alphabetical characters and possibly apostrophes.
* Your spell checker may only take `text` and, optionally, `dictionary` as input. Although you might be inclined (particularly if among those more comfortable) to "pre-process" our default dictionary in order to derive an "ideal hash function" for it, you may not save the output of any such pre-processing to disk in order to load it back into memory on subsequent runs of your spell checker in order to gain an advantage.
* Your spell checker may not leak any memory.
* You may search for (good) hash functions online, so long as you cite the origin of any hash function you integrate into your own code.

Alright, ready to go?

. Implement `load`.
. Implement `check`.
. Implement `size`.
. Implement `unload`.

== Walkthrough

Note that the following embed is a playlist of multiple videos that you should all watch!

[role="embed-responsive embed-responsive-21by9"]
video::u9-1U1Rgo1o[youtube,list=PLhQjrBD2T382vvokQIExRCKZq-q8PzSVz]

== Hints

Be sure to `free` in `unload` any memory that you allocated in `load`! Recall that `valgrind` is your newest best friend. Know that `valgrind` watches for leaks while your program is actually running, so be sure to provide command-line arguments if you want `valgrind` to analyze `speller` while you use a particular `dictionary` and/or text, as in the below. Best to use a small text, though, else `valgrind` could take quite a while to run.

[source]
----
valgrind ./speller texts/ralph.txt
----

If you run `valgrind` without specifying a `text` for `speller`, your implementations of `load` and `unload` won't actually get called (and thus analyzed).

== Testing

How to check whether your program is outting the right misspelled words? Well, you're welcome to consult the "answer keys" that are inside of the `keys` directory that's inside of your `speller` directory. For instance, inside of `keys/lalaland.txt` are all of the words that your program _should_ think are misspelled.

You could therefore run your program on some text in one window, as with the below.

[source]
----
./speller texts/lalaland.txt
----

And you could then compare the `keys/lalaland.txt` and your output visually side by side. That could get tedious quickly, though. So you might instead want to "redirect" your program's output to a file, as with the below.

[source]
----
./speller texts/lalaland.txt > student.txt
----

You can then compare both files side by side in the same window with a program like `diff`, as with the below.

[source]
----
diff -y student.txt keys/lalaland.txt
----

If your program's output matches the staff's, `diff` will output two columns that should be identical except for, perhaps, the running times at the bottom. If the columns differ, though, you'll see a `>` or `|` where they differ. For instance, if you see

[source]
----
MISSPELLED WORDS                                                MISSPELLED WORDS

TECHNO                                                          TECHNO
L                                                               L
                                                              > Thelonious
Prius                                                           Prius
                                                              > MIA
L                                                               L
----

that means your program (whose output is on the left) does not think that `Thelonious` or `MIA` is misspelled, even though the staff's output (on the right) does, as is implied by the absence of, say, `Thelonious` in the lefthand column and the presence of `Thelonious` in the righthand column.

=== `check50`

> If you are on a Mac, please run `check50` on https://code.cs50.io. Underneath the hood `check50` will run `valgrind` for you, but `valgrind` won't work correctly on a Mac.

To test your code less manually (though still not exhaustively), you may also execute the below.

[source]
----
check50 -l minprog/checks/2022/speller
----

Note that `check50` will also check for memory leaks, so be sure you've run `valgrind` as well.

== Big Board

If you'd like to put your code to the test against classmates' code (just for fun), upload your solution to our https://bigboard.quinner.nl/[Big Board] website before or after you submit!

++++
<hr>

<p><b>LET OP. Zoals in de studiewijzer vermeld zijn er redelijke en onredelijke acties wat betreft werken aan de opdrachten. Heel specifiek is het nooit toegestaan om een uitwerking van iemand anders te bekijken terwijl je zelf de opdracht nog aan het maken bent.</b></p>

<p>Bij het inleveren geef je hier aan dat je tijdens het maken van de opdracht niet naar een bestaande uitwerking van de opdracht hebt gekeken, met uitzondering van het zoeken naar en overnemen van een hashfunctie (met bronvermelding).</p>

<p>Als je de opdracht toch wil inleveren terwijl je naar (delen van) bestaande uitwerkingen hebt gekeken dan moet je deze expliciet linken in een comment bij de opdracht en bovenaan de opdracht vermelden dat je dit hebt gedaan. Je zult dan sowieso geen punten krijgen voor de gehele opdracht. Stuur je per ongeluk een versie in zonder deze comments dan gaat de uitwerking naar de examencommissie.</p>

<p><b>Lees de tekst van de checkbox goed voordat je deze aanvinkt. Ingeleverde opdrachten zonder vinkje worden als niet ingestuurd beschouwd.</b></p>

<label for="geen_plagiaat"> <input type="checkbox" required id="geen_plagiaat" name="form[geen_plagiaat]" value="bevestigd"> Ik heb bij het maken van de opdracht geen "onredelijke acties" gepleegd (zie studiewijzer) en specifiek heb ik niet naar een bestaande uitwerking van de opdracht of een klein deel daarvan gekeken (uitgezonderd de hash-functie, die overgenomen mocht worden). Als ik dat wel heb gedaan heb ik in de ingestuurde code overduidelijk de bron aangegeven, maar dan begrijp ik dat ik geen punten krijg. Ik begrijp dat inleveren van de opdracht niet verplicht is en dat ik ook gewoon de punten kan laten lopen.</label>
++++
