= Initials

== tl;dr

Implement a program that, given a person's name, prints a person's initials, per the below.

Before you start coding, make sure that you deeply analyze the exact problem at hand and have a good idea about how your algorithm will solve the problem.

[source]
----
$ ./initials
Name: Regulus Arcturus Black
RAB
----

== Specification

Design and implement a program, `initials`, that, given a person's name, prints a person's initials.

* Implement your program in a file called `initials.c` in a directory called `initials`.
* Your program should prompt a user for their name using `get_string` to obtain their name as a `string`.
* You may assume that the user's input will contain only letters (uppercase and/or lowercase) plus single spaces between words. You don't need to worry about names like `Joseph Gordon-Levitt`, `Conan O'Brien`, or `David J. Malan`!
* Your program should print the user's initials (i.e., the first letter of each word in their name) with no spaces or periods, followed by a newline (`\n`).

== Walkthrough

video::UItYCp0Ivqg[youtube]

== Usage

Your program should behave per the examples below. Assumed that the underlined text is what some user has typed.

[source,subs=quotes]
----
$ [underline]#./initials#
Name: [underline]#Zamyla Chan#
ZC
----

[source,subs=quotes]
----
$ [underline]#./initials#
Name: [underline]#robert thomas bowden#
RTB
----

== Testing

[source]
----
check50 -l minprog/cs50x/2020/initials/less
----
